/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { FrontSide } from 'three'
import { draco } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, require('../assets/3d/env/env_test.glb').default, draco('/draco-gltf/'))
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, -0.36]}>
        <mesh material={materials.mat_bottom_house2} material-roughnessMap={materials.tex_plaster_roughness_ref.map} material-side={FrontSide} geometry={nodes.bottom_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_garage_house2} material-side={FrontSide} geometry={nodes.garage_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_gutter_house2} material-side={FrontSide} geometry={nodes.gutter_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_inside_house2} material-side={FrontSide} geometry={nodes.inside_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_midWall_house2} material-side={FrontSide} geometry={nodes.midWall_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_houseSides_house2} material-side={FrontSide} geometry={nodes.sides_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_sidewalk_house2} material-side={FrontSide} geometry={nodes.sidewalk_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_slabs_house2} material-side={FrontSide} geometry={nodes.slabs_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_trim_house2} material-side={FrontSide} geometry={nodes.trim_house2.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_vent} geometry={nodes.vent_house2.geometry} castShadow receiveShadow />
      </group>
      <group position={[0, 0, 6.97]}>
        <mesh material={materials.mat_vent} geometry={nodes.vent_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_bottom_house1} material-side={FrontSide} geometry={nodes.bottom_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_brick_house1} material-side={FrontSide} geometry={nodes.brick_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_garage_house1} material-side={FrontSide} geometry={nodes.garage_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_glassBlack} material-side={FrontSide} geometry={nodes.garageGlass_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_gutter_house1} material-side={FrontSide} geometry={nodes.gutter_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_inside_house1} material-side={FrontSide} geometry={nodes.inside_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_midWall_house1} material-side={FrontSide} geometry={nodes.midWall_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_roofUnder_house1} material-side={FrontSide} geometry={nodes.roofUnder_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_houseSides_house1} material-side={FrontSide} geometry={nodes.sides_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_sidewalk_house1} material-side={FrontSide} geometry={nodes.sidewalk_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_stairs_house1} material-side={FrontSide} geometry={nodes.stairs_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_trim2_house1} material-side={FrontSide} geometry={nodes.trim2_house1.geometry} castShadow receiveShadow/>
        <mesh material={materials.mat_trim_house1} material-side={FrontSide} geometry={nodes.trim_house1.geometry} castShadow receiveShadow/>
      </group>
      <group position={[0, 0, -7.53]}>
        <mesh material={materials.mat_vent} geometry={nodes.vent_house3.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_gutter_house3} material-side={FrontSide} geometry={nodes.gutter_house3.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_inside_house3} material-side={FrontSide} geometry={nodes.inside_house3.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_houseSides_house3} material-side={FrontSide} geometry={nodes.sides_house3.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_sidewalk_house3} material-side={FrontSide} geometry={nodes.sidewalk_house3.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_terracotta_house3} geometry={nodes.terracotta_house3.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_trim_house3} material-side={FrontSide} geometry={nodes.trim_house3.geometry} castShadow receiveShadow />
        <mesh material={materials.mat_wall_house3} material-side={FrontSide} geometry={nodes.wall_house3.geometry} castShadow receiveShadow />
      </group>
      <mesh material={materials.mat_sidewalk} material-normalScale-x={5} material-normalScale-y={5} material-roughness={0.7} material-roughnessMap={materials.tex_sidewalk1_roughness_ref.map} material-side={FrontSide} geometry={nodes.sidewalk_main.geometry} receiveShadow />
      <mesh material={materials.mat_sidewalk} material-roughnessMap={materials.tex_sidewalk1_roughness_ref.map} material-side={FrontSide} geometry={nodes.sidewalkCut.geometry} receiveShadow position={[0, 0, 3.35]} />
      <mesh material={materials.mat_sidewalk} material-roughnessMap={materials.tex_sidewalk1_roughness_ref.map} material-side={FrontSide} geometry={nodes.sidewalkPlanters.geometry} receiveShadow position={[0, 0, -3.35]} />
      <mesh material={materials.mat_curb} material-roughnessMap={materials.tex_sidewalk1_roughness_ref.map} material-side={FrontSide} geometry={nodes.curb.geometry} receiveShadow />
      <mesh material={materials.mat_curb} material-roughnessMap={materials.tex_sidewalk1_roughness_ref.map} material-side={FrontSide} geometry={nodes.curb_cut.geometry} receiveShadow position={[0, 0, 3.35]} />
      <mesh material={materials.mat_road} material-roughnessMap={materials.tex_road_roughness_ref.map} material-side={FrontSide} geometry={nodes.road.geometry} receiveShadow />
      <mesh material={materials.mat_planter} material-roughnessMap={materials.tex_dirt_roughness_ref.map} material-side={FrontSide} geometry={nodes.dirt.geometry} receiveShadow position={[0, 0, -3.35]} />
      {/* <mesh
        material={materials.tex_cloud_ref}
        geometry={nodes.tex_cloud_ref2.geometry}
        position={[7.04, 1.89, -2.03]}
      />
      <mesh
        material={materials.tex_plaster_roughness_ref}
        geometry={nodes.tex_plaster_roughness_ref.geometry}
        position={[7.04, 1.89, 0.2]}
      />
      <mesh
        material={materials.tex_woodPlanks_normal_ref}
        geometry={nodes.tex_woodPlanks_normal_ref.geometry}
        position={[9.29, 1.89, 2.41]}
      />
      <mesh
        material={materials.tex_brick_roughness_ref}
        geometry={nodes.tex_brick_roughness_ref.geometry}
        position={[7.04, 1.89, 4.65]}
      />
      <mesh
        material={materials.tex_woodPlanks_roughness_ref}
        geometry={nodes.tex_woodPlanks_roughness_ref.geometry}
        position={[7.04, 1.89, 2.41]}
      />
      <mesh
        material={materials.tex_plaster_normal}
        geometry={nodes.tex_plaster_normal.geometry}
        position={[9.29, 1.89, 0.2]}
      />
      <mesh
        material={materials.tex_road_roughness_ref}
        geometry={nodes.tex_road_roughness_ref.geometry}
        position={[7.04, 1.89, -4.24]}
      />
      <mesh
        material={materials.tex_brick_diffuse_ref}
        geometry={nodes.tex_brick_diffuse_ref.geometry}
        position={[9.29, 1.89, 4.65]}
      />
      <mesh
        material={materials.tex_brick_normal_ref}
        geometry={nodes.tex_brick_normal_ref.geometry}
        position={[11.52, 1.89, 4.65]}
      />
      <mesh
        material={materials.tex_sidewalk1_roughness_ref}
        geometry={nodes.tex_sidewalk1_roughness_ref.geometry}
        position={[9.29, 1.89, -2.03]}
      />
      <mesh
        material={materials.tex_dirt_roughness_ref}
        geometry={nodes.tex_dirt_roughness_ref.geometry}
        position={[7.04, 1.89, -6.46]}
      />
      <mesh
        material={materials.tex_brickSmall_roughness_ref}
        geometry={nodes.tex_brickSmall_roughness_ref.geometry}
        position={[7.04, 1.89, 6.89]}
      />
      <mesh
        material={materials.tex_brickSmall_diffuse_ref}
        geometry={nodes.tex_brickSmall_diffuse_ref.geometry}
        position={[9.29, 1.89, 6.89]}
      />
      <mesh
        material={materials.tex_brickSmall_normal_ref}
        geometry={nodes.tex_brickSmall_normal_ref.geometry}
        position={[11.52, 1.89, 6.89]}
      /> */}
    </group>
  )
}
