/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { FrontSide } from 'three'

export default function Serve(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('serve.glb')
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.26, 0]}>
        <group position={[0.16, 0, 0]}>
          <group position={[0.02, -0.11, 0.23]}>
            <mesh geometry={nodes.cap_fl.geometry} material={nodes.cap_fl.material} />
            <mesh geometry={nodes.hub_fl.geometry} material={nodes.hub_fl.material} />
            <mesh geometry={nodes.tire_fl.geometry} material={nodes.tire_fl.material} />
          </group>
          <group position={[0.02, -0.11, -0.23]}>
            <mesh geometry={nodes.cap_rl.geometry} material={nodes.cap_rl.material} />
            <mesh geometry={nodes.hub_rl.geometry} material={nodes.hub_rl.material} />
            <mesh geometry={nodes.tire_rl.geometry} material={nodes.tire_rl.material} />
          </group>
          <mesh
            geometry={nodes.boggy_arm_l.geometry}
            material={nodes.boggy_arm_l.material}
            position={[-0.16, -0.26, 0]}
          />
        </group>
        <group position={[-0.16, 0, 0]}>
          <group position={[-0.02, -0.11, 0.23]}>
            <mesh geometry={nodes.cap_fr.geometry} material={nodes.cap_fr.material} />
            <mesh geometry={nodes.hub_fr.geometry} material={nodes.hub_fr.material} />
            <mesh geometry={nodes.tire_fr.geometry} material={nodes.tire_fr.material} />
          </group>
          <group position={[-0.02, -0.11, -0.23]}>
            <mesh geometry={nodes.cap_rr.geometry} material={nodes.cap_rr.material} />
            <mesh geometry={nodes.hub_rr.geometry} material={nodes.hub_rr.material} />
            <mesh geometry={nodes.tire_rr.geometry} material={nodes.tire_rr.material} />
          </group>
          <mesh
            geometry={nodes.boggy_arm_r.geometry}
            material={nodes.boggy_arm_r.material}
            position={[0.16, -0.26, 0]}
          />
        </group>
        <group position={[0, 0.55, -0.33]}>
          <mesh geometry={nodes.lid_inside.geometry} material={nodes.lid_inside.material} position={[0, -0.81, 0.33]} />
          <mesh geometry={nodes.lid_liner.geometry} material={nodes.lid_liner.material} position={[0, -0.81, 0.33]} />

          {/* Lid */}
          <mesh geometry={nodes.lid_top.geometry} material={materials.mat_lid_vinyl} position={[0, -0.81, 0.33]} />
          <mesh geometry={nodes.lid_top.geometry} material={materials.mat_lid_base} position={[0, -0.81, 0.33]} />

          <mesh geometry={nodes.strip.geometry} material={nodes.strip.material} position={[0, -0.81, 0.33]} />
        </group>
        <mesh geometry={nodes.aluminum.geometry} material={nodes.aluminum.material} position={[0, -0.26, 0]} />

        {/* Bin */}
        <mesh geometry={nodes.bin.geometry} material={materials.mat_bin_vinyl} position={[0, -0.26, 0]} />
        <mesh geometry={nodes.bin.geometry} material={materials.mat_bin_base} position={[0, -0.26, 0]} />

        <mesh geometry={nodes.black_glass.geometry} material={materials.mat_lense} position={[0, -0.26, 0]} />
        <mesh
          geometry={nodes.black_plastic.geometry}
          material={nodes.black_plastic.material}
          position={[0, -0.26, 0]}
        />
        <mesh
          geometry={nodes.black_plastic_base.geometry}
          material={nodes.black_plastic_base.material}
          position={[0, -0.26, 0]}
        />
        <mesh geometry={nodes.blocker.geometry} material={materials.mat_light_blocker} position={[0, -0.26, 0]} />
        <mesh geometry={nodes.eye_lense.geometry} material={nodes.eye_lense.material} position={[0, -0.26, 0]} />
        <mesh geometry={nodes.eye_plate.geometry} material={materials.mat_metal_black_rough} position={[0, -0.26, 0]} />
        <mesh geometry={nodes.front_decal.geometry} material={materials.mat_front_decal} material-color={0xFFFFFF} material-transparent={true} position={[0, -0.26, 0]} />
        <mesh geometry={nodes.liner.geometry} material={nodes.liner.material} position={[0, -0.26, 0]} />
        <mesh
          geometry={nodes.rear_bottom_decal.geometry}
          material={materials.mat_rear_bottom_decal}
          material-color={0xFFFFFF} 
          material-transparent={true}
          position={[0, -0.26, 0]}
        />
        <mesh
          geometry={nodes.rear_top_decal.geometry}
          material={materials.mat_rear_top_decal}
          material-color={0xFFFFFF} 
          material-transparent={true}
          position={[0, -0.26, 0]}
        />
        <mesh geometry={nodes.screen.geometry} material={materials.mat_screen} position={[0, -0.26, 0]} />
        <mesh geometry={nodes.tail_lights.geometry} material={materials.mat_tail_lights} position={[0, -0.26, 0]} />
      </group>
      <mesh geometry={nodes.floor.geometry} material={materials.mat_floor} material-side={FrontSide} material-color={0x000000} material-alphaMap={materials.tex_floor_ref.map} />
    </group>
  )
}

useGLTF.preload('serve.glb')
